# Generated by Django 4.2.6 on 2023-10-31 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0002_clause_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clause',
            old_name='date_added',
            new_name='pub_date',
        ),
    ]
